### ISSUE TITLE
Tokenizer passes identifiers which starts with a digit

### ISSUE THREAD

**Issue by tdakkota** [serid/mt1#1]
[Spec](https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.8)

_An identifier is an unlimited-length sequence of Java letters and Java digits, **the first of which must be a Java letter**._

https://github.com/serid/mt1/blob/7499fbdbda1dd4e5354bcfd1124336648291b084/src/net/serid/mt1/compile/parse/tokenize/Tokenizer.java#L50-L56

Use [`Character.isJavaIdentifierStart`](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isJavaIdentifierStart(int)) and  [`Character.isJavaIdentifierStart`](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isJavaIdentifierPart(int))

**Comment by serid** [comment]
@tdakkota Whatever you say, friend.
